# -*- coding: utf-8 -*-
"""simple Rock, paper, scissors on python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fabSPa6VYZwWzD14486ISsJj74wvWd7H
"""

import random

choises = ['rock', 'paper', 'scissors']
points = {'computer': 0, 'player': 0}

while True:
    computer = random.choice(choises)
    player = None

    while player not in choises:
        player = input('Rock, paper or scissors? >> ').lower()

    print(f'computer: {computer}')
    print(f'player: {player}')

    if player == computer:
        print('Not bad, not good. Tie!')
    elif player == 'rock':
        if computer == 'paper':
            print('Ha-ha! You lose!')
            points['computer'] += 1
        else:
            print('Good job! You win!')
            points['player'] += 1
    elif player == 'paper':
        if computer == 'scissors':
            print('Ha-ha! You lose!')
            points['computer'] += 1
        else:
            print('Good job! You win!')
            points['player'] += 1
    else:
        if computer == 'rock':
            print('Ha-ha! You lose!')
            points['computer'] += 1
        else:
            print('Good job! You win!')
            points['player'] += 1
    
    playAgain = input('Do you want to play again? (yes/no) >> ').lower()
    print('')
    if playAgain != 'yes':
        break

print('Game over! Bye!')
print('Total points:')
print('computer:', points['computer'])
print('player:', points['player'])